### ISSUE TITLE
Typing in an Entry field is very slow when navigationbar is enabled in Android

### ISSUE THREAD

**Issue by gihanwijesinghe** [Microsoft/SmartHotel360-Mobile#61]
If line 12 of SmartHotel.Clients.Views.BookingView.xaml.cs changed as NavigationPage.SetHasNavigationBar(this, true); , whole view gets slow. specially entry field (search box)

**Comment by dasanagu** [comment]
Fixed with commit [c6b9a3](https://github.com/Microsoft/SmartHotel360-Mobile/commit/c6b9a34a1667fc2ac2e241a8c5f15a350316d54e). Thank you for the PR!
