### ISSUE TITLE
Previewer VS Mac error about nuget reference

### ISSUE THREAD

**Issue by nrushforth** [Microsoft/SmartHotel360-Mobile#65]
I am trying to preview the xaml files in the previewer and for the majority of the xaml files I see the following error
<img width="665" alt="screenshot 2018-11-30 at 22 04 20" src="https://user-images.githubusercontent.com/12371225/49317381-2715cf00-f4ec-11e8-9183-51df5a3511ea.png">

I am seeing this issue in VS Mac 7.7.

**Comment by pulimento** [comment]
Hi @nrushforth, thanks for testing our code. Unfortunately, the XAML Previewer in VS for Mac is in preview, and in development. In the current state, it may be bugs, as the one you have just described. AFAIK, this is a IDE error, not a SmartHotel one. Sorry por that, and we hope to improve that part of the tooling in the near future. Will close this issue now.
