### ISSUE TITLE
Does not build on Windows 10, lots of error

### ISSUE THREAD

**Issue by mach37** [Microsoft/SmartHotel360-Mobile#66]
Hello can you please update the nugets and references and check in with more detail step. 

For a benchmark & ;earning microsoft application, this has a lot of errors!

**Comment by pulimento** [comment]
Hi @mach37. I've just cloned the code, and ran it on VS 2017 with no errors at all, the app seems to run just fine. I tried the Windows 10 (UWP version) and the Android one, with no errors so far. 

What are the errors you are facing? Why you can't build it? Please give me some information (VS version, your environment, build logs, etc...) so I can help you better. Thanks

**Comment by mach37** [comment]
Hi I tried again, the build failed for me because of the (I think) Nuget version inconsistencies. When I update one the rest need to be updated and it does not build

Is there some steps to follow that specific to this, please let me know.

Thanks for your help.

**Comment by pulimento** [comment]
Please, see #73
