### ISSUE TITLE
What is the minimum android version this app works on?

### ISSUE THREAD

**Issue by nitinjs** [microsoft/SmartHotel360-Mobile#76]
What is the minimum android version this app works on?

**Comment by pulimento** [comment]
Currently, you need at least Android 4.0.3 (Ice Cream, API version 15) to run this app, so virtually any actual device should do the trick! [This is the line of the manifest that establishes it](https://github.com/microsoft/SmartHotel360-Mobile/blob/master/Source/SmartHotel.Clients/SmartHotel.Clients.Android/Properties/AndroidManifest.xml#L3)
