### ISSUE TITLE
Sample endpoint not working

### ISSUE THREAD

**Issue by matteopiccioni** [microsoft/SmartHotel360-Mobile#77]
Hello,
Id like to try the app live,
but when I make login an error accours: 'An error acurred, try again', even using real microsoft account.
And the sample endpoint is not working too.
Thanks

**Comment by chrfrenning** [comment]
Are you building the clients yourself or using the AppCenter binaries? iOS or Droid?

**Comment by matteopiccioni** [comment]
I build the SmartHootem.Clients.iOS myself, 
using latest visual studio for Mac and using master branch

Installation is fine..With 'production' end point, in login page I can put anything..when I go in the next pages I always have  'An error acurred, try again' message.

The sample endpoint 'http://sh360services-public.eastus2.cloudapp.azure.com/configuration-api/cfg/public-http' is not working too...if I put the link in browser I can see that the page doesnt exist
Thanks!

**Comment by pulimento** [comment]
Sorry to hear that, but you're not using the latest version of the app.
Older versions are known to fail, changes has been done to backend endpoints.
Please, try the last version of the code in the master branch, or use the AppCenter relases.
Thanks for trying our code!
