### ISSUE TITLE
Forms 4 - Shell

### ISSUE THREAD

**Issue by prom3theu5** [microsoft/SmartHotel360-Mobile#83]
This is awesome. 
Are there plans to port it to Shell, in XamForms 4.0?

**Comment by dasanagu** [comment]
Thank you! For Xamarin.Forms 4 we use [Tailwind Traders ](https://github.com/microsoft/TailwindTraders-Mobile)

**Comment by prom3theu5** [comment]
Ahh cool. Thanks a lot :)
